# Generated by Django 2.2.6 on 2019-10-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autographed', models.BooleanField(default=False)),
                ('condition', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('number', models.CharField(max_length=32)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('quantity', models.IntegerField()),
                ('player', models.CharField(max_length=32)),
                ('team', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
            ],
        ),
    ]
