# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandname',
            old_name='band_name',
            new_name='brand_name',
        ),
    ]
