version: '3.8'

services:
  api:
    build: .
    command: poetry run gunicorn bbct.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - api
