version: '3.8'

services:
  api:
    build: .
    command: poetry run gunicorn bbct.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - api
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bbct
      - POSTGRES_PASSWORD=bbct
      - POSTGRES_DB=bbct

volumes:
  postgres_data:
